int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int _get_root(int m, int n);
int _check_prime(int p, int q);
int _wild_cmp_check(char *s1, char *s2, int i, int j);
